#!/usr/bin/with-contenv bash

if [[ ! dpkg --get-selections | grep -q "^build-essential[[:space:]]*install$" >/dev/null ]] && \
[ -f /usr/bin/apt ]; then
  ## Ubuntu
  apt-get update
  apt-get install --no-install-recommends -y \
    build-essential
fi
